#!/bin/sh
set -eu
. "$TEST_ROOT/tests/fixtures.sh"

for command in set get ls; do
    case $command in
        ls) set -- ls ;;
        *) set -- "$command" FIRST ;;
    esac
    if "$ENVY_BIN" "$@" < /dev/null > before.out 2> before.err; then
        fail 'store command succeeded before init'
    fi
    grep 'store not initialized; run envy init' before.err > /dev/null || fail 'missing initialization advice'
    [ ! -s before.out ] || fail 'uninitialized command wrote stdout'
done
if "$ENVY_BIN" init > no-url.out 2> no-url.err; then
    fail 'init accepted a missing URL'
fi
if "$ENVY_BIN" init "$HOME/absent.git" > absent.out 2> absent.err; then
    fail 'init accepted an unreachable repository'
fi
[ ! -e "$XDG_DATA_HOME/envy/store" ] || fail 'failed clone left a store'
[ ! -e "$XDG_DATA_HOME/envy/identity" ] || fail 'failed clone left an identity'

# Nonstandard paths, including spaces, must control where local state lives.
XDG_DATA_HOME=$HOME/custom\ data
XDG_CONFIG_HOME=$HOME/custom\ config
XDG_STATE_HOME=$HOME/custom\ state
export XDG_DATA_HOME XDG_CONFIG_HOME XDG_STATE_HOME
python3 "$TEST_ROOT/tests/pty-helper.py" -- "$ENVY_BIN" init "$TEST_REMOTE" <<'RESPONSES'
throwaway-store-passphrase
throwaway-store-passphrase
RESPONSES
store=$XDG_DATA_HOME/envy/store
identity=$XDG_DATA_HOME/envy/identity
[ -f "$identity" ] || fail 'identity absent from data directory'
[ ! -e "$HOME/.local/share/envy/identity" ] || fail 'XDG data directory ignored'
[ ! -e "$XDG_CONFIG_HOME/envy/identity" ] || fail 'identity saved under config'
python3 - "$identity" <<'PY'
import os
import stat
import sys
metadata = os.stat(sys.argv[1])
assert stat.S_IMODE(metadata.st_mode) == 0o600
assert metadata.st_uid == os.getuid()
PY
assert_equal "$(git --git-dir="$TEST_REMOTE" show HEAD:format)" 1 'format marker not pushed'
git --git-dir="$TEST_REMOTE" show HEAD:recipient > pushed-recipient
age-keygen -y "$identity" > local-recipient
cmp pushed-recipient local-recipient || fail 'pushed recipient differs from local identity'
git --git-dir="$TEST_REMOTE" show HEAD:identity.age > pushed-identity.age
grep '^-----BEGIN AGE ENCRYPTED FILE-----' pushed-identity.age > /dev/null || fail 'identity is not armored'
python3 "$TEST_ROOT/tests/pty-helper.py" -- age -d -o unlocked pushed-identity.age <<'RESPONSES'
throwaway-store-passphrase
RESPONSES
cmp "$identity" unlocked || fail 'encrypted identity cannot be recovered'
assert_equal "$(git --git-dir="$TEST_REMOTE" rev-list --count HEAD)" 1 'init did not make exactly one commit'
assert_equal "$(git --git-dir="$TEST_REMOTE" log -1 --format=%s)" 'init store' 'init commit message'
assert_equal "$(git -C "$store" config --local user.name)" envy 'missing git author name was not supplied locally'
assert_equal "$(git -C "$store" config --local user.email)" envy@localhost 'missing git author email was not supplied locally'
[ ! -e "$HOME/.gitconfig" ] || fail 'init changed global git config'
assert_equal "$(git -C "$store" status --porcelain)" '' 'init left uncommitted files'
git --git-dir="$TEST_REMOTE" ls-tree -r --name-only HEAD > tree
printf 'format\nidentity.age\nrecipient\n' > expected-tree
cmp expected-tree tree || fail 'init pushed unexpected files'
"$ENVY_BIN" ls > empty-list
[ ! -s empty-list ] || fail 'new store list is not empty'
revision=$(git -C "$store" rev-parse HEAD)
if "$ENVY_BIN" init "$TEST_REMOTE" > again.out 2> again.err; then
    fail 'init overwrote an existing local store'
fi
assert_equal "$(git -C "$store" rev-parse HEAD)" "$revision" 'repeated init changed store'
cmp "$identity" unlocked || fail 'repeated init replaced identity'

# A blank response must use age's generated passphrase, without confirmation.
fixture_remote "$HOME/generated.git"
XDG_DATA_HOME=$HOME/generated-data
export XDG_DATA_HOME
python3 "$TEST_ROOT/tests/pty-helper.py" --transcript generated-terminal \
    -- "$ENVY_BIN" init "$HOME/generated.git" <<'RESPONSES'

RESPONSES
python3 - generated-terminal generated-response <<'PY'
import re
import sys
with open(sys.argv[1], "rb") as transcript:
    output = transcript.read()
assert b"autogenerate" in output
match = re.search(rb'[Uu]sing (?:the )?autogenerated passphrase[ :]*"([^"\r\n]+)"', output)
assert match is not None
with open(sys.argv[2], "wb") as response:
    response.write(match.group(1).strip() + b"\n")
PY
python3 "$TEST_ROOT/tests/pty-helper.py" -- age -d -o generated-unlocked \
    "$XDG_DATA_HOME/envy/store/identity.age" < generated-response
cmp "$XDG_DATA_HOME/envy/identity" generated-unlocked || fail 'generated passphrase did not recover identity'

# When XDG variables are absent, use the user's default data directory.
fixture_remote "$HOME/default.git"
unset XDG_DATA_HOME XDG_CONFIG_HOME XDG_STATE_HOME
git config --global user.name 'Configured User'
git config --global user.email configured@example.invalid
python3 "$TEST_ROOT/tests/pty-helper.py" -- "$ENVY_BIN" init "$HOME/default.git" <<'RESPONSES'
default-throwaway-passphrase
default-throwaway-passphrase
RESPONSES
[ -f "$HOME/.local/share/envy/identity" ] || fail 'default data directory not used'
assert_equal "$(git --git-dir="$HOME/default.git" log -1 --format=%an)" 'Configured User' 'configured author name ignored'
assert_equal "$(git --git-dir="$HOME/default.git" log -1 --format=%ae)" configured@example.invalid 'configured author email ignored'

# A repository with commits on another branch is populated even if HEAD is unborn.
XDG_DATA_HOME=$HOME/existing-data
export XDG_DATA_HOME
git --git-dir="$TEST_REMOTE" symbolic-ref HEAD refs/heads/unborn
if "$ENVY_BIN" init "$TEST_REMOTE" < /dev/null > unborn.out 2> unborn.err; then
    fail 'init treated an unborn HEAD as an empty repository'
fi
grep 'store not initialized' unborn.err > /dev/null || fail 'unborn checkout not diagnosed'
[ ! -e "$XDG_DATA_HOME/envy/identity" ] || fail 'unborn HEAD caused identity creation'
[ ! -e "$XDG_DATA_HOME/envy/store" ] || fail 'unborn checkout left a store'
